nf_core_version: 3.3.2
repository_type: pipeline
lint:
  schema_params: false
  nf_test_content: false
template:
  author: Praveen Raj, Maxime U Garcia, Nicolas Vannieuwkerke
  description: GATK4 RNA variant calling pipeline
  force: false
  is_nfcore: true
  name: rnavar
  org: nf-core
  outdir: .
  version: 1.2.0dev
