nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Praveen Raj, Maxime U Garcia
  description: GATK4 RNA variant calling pipeline
  force: false
  is_nfcore: true
  name: rnavar
  org: nf-core
  outdir: .
  version: 2.0.0dev
