/*
========================================================================================
    RECALIBRATE
========================================================================================
*/

include { GATK4_APPLYBQSR } from '../../../modules/nf-core/gatk4/applybqsr'
include { SAMTOOLS_INDEX  } from '../../../modules/nf-core/samtools/index'
include { SAMTOOLS_STATS  } from '../../../modules/nf-core/samtools/stats'

/**
 * Apply base quality score recalibration (BQSR) to BAM files.
 *
 * This subworkflow applies the BQSR model generated by GATK BaseRecalibrator
 * to adjust base quality scores in BAM files. Recalibrated quality scores
 * improve the accuracy of variant calling by correcting systematic errors
 * in the original quality scores assigned by the sequencing machine.
 *
 * Optionally generates alignment statistics using samtools stats for QC.
 *
 * @param skip_samtools Whether to skip samtools stats generation
 * @param bam Input BAM file with recalibration table
 * @param dict Reference genome sequence dictionary
 * @param fai Reference genome FASTA index
 * @param fasta Reference genome FASTA file
 */
workflow RECALIBRATE {
    take:
    skip_samtools // boolean: true/false
    bam // channel: [mandatory] bam
    dict // channel: [mandatory] dict
    fai // channel: [mandatory] fai
    fasta // channel: [mandatory] fasta

    main:

    def ch_reports = channel.empty()
    def ch_versions = channel.empty()

    GATK4_APPLYBQSR(
        bam,
        fasta,
        fai,
        dict,
    )

    SAMTOOLS_INDEX(GATK4_APPLYBQSR.out.bam)

    def bam_indices = SAMTOOLS_INDEX.out.bai
        .mix(SAMTOOLS_INDEX.out.csi)
        .mix(SAMTOOLS_INDEX.out.crai)

    def bam_recalibrated_index = GATK4_APPLYBQSR.out.bam.join(bam_indices, failOnMismatch: true, failOnDuplicate: true)

    ch_versions = ch_versions.mix(GATK4_APPLYBQSR.out.versions)
    ch_versions = ch_versions.mix(SAMTOOLS_INDEX.out.versions)

    if (!skip_samtools) {
        SAMTOOLS_STATS(bam_recalibrated_index, [[], []])
        ch_reports = SAMTOOLS_STATS.out.stats
    }

    emit:
    bam      = bam_recalibrated_index
    qc       = ch_reports
    versions = ch_versions
}
